config/routes.rb
Rails.application.routes.draw do

  resources :ordens

  get 'stocks/movimientos'

  resources :stocks

  resources :productos

  get 'inicio/inicio'

  devise_for :users

  root 'inicio#inicio'

end

app/models/orden.rb
class Orden < ActiveRecord::Base

  has_many :ordenproductos
  has_many :productos,through: :ordenproductos

  accepts_nested_attributes_for :ordenproductos,:reject_if => :all_blank,:allow_destroy => true

end

app/models/ordenproducto.rb
class Ordenproducto < ActiveRecord::Base

  belongs_to :producto,foreign_key: :producto_id
  belongs_to :orden,foreign_key: :orden_id

end

app/models/producto.rb
class Producto < ActiveRecord::Base
  has_many :stock
  has_many :ordenproductos
  has_many :ordens,through: :ordenproductos

end

app/models/stock.rb
class Stock < ActiveRecord::Base
belongs_to :producto,foreign_key: :producto_id
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  layout 'superhero'
  before_filter :authenticate_user!
end

app/controllers/inicio_controller.rb
class InicioController < ApplicationController
  def inicio
  end
end

app/controllers/ordens_controller.rb
class OrdensController < ApplicationController
  before_action :set_orden, only: [:show, :edit, :update, :destroy]
  respond_to :html, :xml, :json
  def index
    @ordens = Orden.all
    respond_with(@ordens)
  end

  def show
    respond_with(@orden)
  end

  def new
    @orden = Orden.new
    respond_with(@orden)
  end

  def edit
  end

  def create
    @orden = Orden.new(orden_params)
    @orden.save
    respond_with(@orden)
  end

  def update
    @orden.update(orden_params)
    respond_with(@orden)
  end

  def destroy
    @orden.destroy
    respond_with(@orden)
  end

  private
    def set_orden
      @orden = Orden.find(params[:id])
    end

    def orden_params
      params.require(:orden).permit(:fecha_uso, :user_id, ordenproductos_attributes: [:id,:producto_id, :orden_id, :cantidad,:done, :_destroy])
    end
end

app/controllers/productos_controller.rb
class ProductosController < ApplicationController
  before_action :set_producto, only: [:show, :edit, :update, :destroy]
  respond_to :html, :xml, :json
  def index
    respond_with(@productos = Producto.all)
  end

  def show
    respond_with(@producto)
  end

  def new
    @producto = Producto.new
    respond_with(@producto)
  end

  def edit
  end

  def create
    @producto = Producto.new(producto_params)
    @producto.save
    respond_with(@producto)
  end

  def update
    @producto.update(producto_params)
    respond_with(@producto)
  end

  def destroy
    @producto.destroy
    respond_with(@producto)
  end

  private
    def set_producto
      @producto = Producto.find(params[:id])
    end

    def producto_params
      params.require(:producto).permit(:nombre, :precio)
    end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  before_action :set_stock, only: [:show, :edit, :update, :destroy]
  respond_to :html, :xml, :json

  def index
    respond_with(@stocks = Stock.group(:producto_id))
  end

  def show
    respond_with(@stock)
  end

  def movimientos
    @stocks = Stock.all
    respond_with(@stock)
  end

  def new
    @stock = Stock.new
    respond_with(@stock)
  end

  def edit
  end

  def create
    @stock = Stock.new(stock_params)
    @stock.save
    respond_with(@stock)
  end

  def update
    @stock.update(stock_params)
    respond_with(@stock)
  end

  def destroy
    @stock.destroy
    respond_with(@stock)
  end

  private
    def set_stock
      @stock = Stock.find(params[:id])
    end

    def stock_params
      params.require(:stock).permit(:cantidad, :producto_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inicio_helper.rb
module InicioHelper
end

app/helpers/ordens_helper.rb
module OrdensHelper
end

app/helpers/productos_helper.rb
module ProductosHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/inicio/inicio.html.erb
<h1>Inicio#inicio</h1>
<p>Find me in app/views/inicio/inicio.html.erb</p>

app/views/layouts/superhero.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "comedor" %></title>
<hr>    <%= csrf_meta_tags %>


<div class="container">
    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "superhero", :media => "all" %>

    <%= yield(:page_stylesheet) if content_for?(:page_stylesheet) %>

  </head>
  <body>


    <%= yield %>

    <!-- Fixed navbar -->
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">

        <div class="navbar-header">

          <a href="../" class="navbar-brand">Comedor-UNCAus</a>

        </div>

        <% if user_signed_in? %>

        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Stock<b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><%= link_to 'Ver Stock',stocks_path%></li>
                <li><%= link_to 'Agregar Stock',new_stock_path%></li>
                <li class="divider"></li>
                <li class="dropdown-header">Nav header</li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li>

            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Ordenes<b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><%= link_to 'Listar Órdenes', ordens_path%></li>
                <li><%= link_to 'Nueva Órden', new_orden_path%></li>

                <li class="divider"></li>
                <li class="dropdown-header">Nav header</li>
              </ul>
            </li>

            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Productos <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><%= link_to 'Ver Productos', productos_path%></li>
                <li><%= link_to 'Agregar Productos', new_producto_path%></li>

                <li class="divider"></li>
                <li class="dropdown-header">Nav header</li>
              </ul>
            </li>

            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Logueado como: <%= current_user.email%><b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><%= link_to 'Cerrar Sesión', destroy_user_session_path, method: :delete%></li>
              </ul>
            </li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>


    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "superhero" %>
    <%= yield(:page_javascript) if content_for?(:page_javascript) %>
  </body>
</html>



<script type="text/javascript">
    $(document).ready(function() {
        $('select#producto-select').select2({
            placeholder: "Elija un producto",
            allowClear: true
        });
    });
</script> 




<!-- Cierro el div container que centra el contenido -->
</div>

<% end %>

app/views/ordens/_form.html.erb
<%= simple_form_for @orden, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :fecha_uso %>
  <%= f.input :user_id %>


    <fieldset>
      <legend>Productos de la Orden</legend>
      <%= f.simple_fields_for :ordenproductos do |ordenproductos| %>
          <%= render 'ordenproducto_fields', f:  ordenproductos %>
      <% end %>

      <p><%= link_to_add_association 'Agregar Producto', f, :ordenproductos %></p> <p></p>

    </fieldset>


    <div class="modal-footer">
      <%= f.submit("Crear Orden", :class => 'btn btn-primary' , :title => "Guarda los datos y envia el pedido." )%>

      <%= link_to("Cancelar", root_path, :class => "btn btn-inverse", :title => "Cancela el pedido y dirige al inicio" )%>
    </div>

    <!-- Cierro el comienzo el form-->
<% end %>

app/views/ordens/_ordenproducto_fields.html.erb
<div class='nested-fields'>
  <table class="table table-condensed">
    <td><%= f.input :producto_id, collection: Producto.order(nombre: :asc), value_method: :id, label_method: :nombre, include_blank: false,input_html: { id: "producto-select" } %></td>
    <td><%= f.input :cantidad, input_html: {:class => 'span4'}%></td>
    <td><%= link_to_remove_association "Quitar producto", f,  :class => 'btn btn-mini btn-danger' %></td>
  </table>
</div>

app/views/ordens/edit.html.erb
<%- model_class = Orden -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/ordens/index.html.erb
<%- model_class = Orden -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:fecha_uso) %></th>
      <th><%= model_class.human_attribute_name(:user_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @ordens.each do |orden| %>
      <tr>
        <td><%= link_to orden.id, orden_path(orden) %></td>
        <td><%= orden.fecha_uso %></td>
        <td><%= orden.user_id %></td>
        <td><%=l orden.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_orden_path(orden), :class => 'btn btn-primary btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      orden_path(orden),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-danger btn-xs' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_orden_path,
            :class => 'btn btn-primary' %>

app/views/ordens/new.html.erb
<%- model_class = Orden -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/ordens/show.html.erb
<%- model_class = Orden -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:fecha_uso) %>:</strong></dt>
  <dd><%= @orden.fecha_uso %></dd>
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @orden.user_id %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              ordens_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_orden_path(@orden), :class => 'btn btn-primary' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              orden_path(@orden),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/productos/_form.html.erb
<%= simple_form_for @producto, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :nombre %>
  <%= f.input :precio %>
    <br/>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                productos_path, :class => 'btn' %>
  </div>
<% end %>

app/views/productos/edit.html.erb
<%- model_class = Producto -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/productos/index.html.erb
<%- model_class = Producto -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Id</th>
      <th>Nombre</th>
      <th>Precio</th>
      <th>Acciones</th>
    </tr>
  </thead>
  <tbody>
    <% @productos.each do |producto| %>
      <tr>
        <td><%= link_to producto.id, producto_path(producto) %></td>
        <td><%= producto.nombre %></td>
        <td><%= producto.precio %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_producto_path(producto), :class => 'btn btn-primary btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      producto_path(producto),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-danger btn-xs' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_producto_path,
            :class => 'btn btn-primary' %>

app/views/productos/new.html.erb
<%- model_class = Producto -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/productos/show.html.erb
<%- model_class = Producto -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:nombre) %>:</strong></dt>
  <dd><%= @producto.nombre %></dd>
  <dt><strong>Precio:</strong></dt>
  <dd><%= @producto.precio %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              productos_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_producto_path(@producto), :class => 'btn btn-primary' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              producto_path(@producto),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/stocks/_form.html.erb
<%= simple_form_for @stock, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :cantidad %>
    <%= f.input :producto_id, collection: Producto.order(nombre: :asc), value_method: :id, label_method: :nombre, include_blank: false,input_html: { id: "producto-select" } %>

    <div class="form-actions"><br>
    <%= f.button :submit, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                stocks_path, :class => 'btn' %>
  </div>
<% end %>



<!-- El script del select está en superhero.html.erb -->

app/views/stocks/edit.html.erb
<%- model_class = Stock -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/stocks/index.html.erb
<%- model_class = Stock -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Cantidad</th>
      <th>Producto</th>
      <th>Fecha_actualizacion</th>
      <th>Acciones</th>
    </tr>
  </thead>
  <tbody>
    <% @stocks.each do |stock| %>
      <tr>
        <td><%= Stock.where(producto_id: stock.producto.id).sum(:cantidad)%></td>
        <td><%= stock.producto.nombre %></td>
        <td><%=l stock.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_stock_path(stock), :class => 'btn btn-primary btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      stock_path(stock),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-danger btn-xs' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_stock_path,
            :class => 'btn btn-primary' %>

app/views/stocks/movimientos.html.erb
<%- model_class = Stock -%>

    <div class="page-header">
      <h2>Movimientos de Stock</h2>
    </div>

        <table class="table table-condensed">
          <thead>
          <tr>
            <th>Id</th>
            <th>Producto</th>
            <th>Cantidad </th>
            <th>Fecha</th>
            <th> </th>
            <!-- <th>Acciones</th> en los movimientos no se pueden realizar acciones-->
          </tr>
          </thead>
          <tbody>

            <% @stocks.each do |stock| %>
                <tr>
                  <td><%= link_to stock.id, stock_path(stock) %></td>
                  <td><%= stock.producto.nombre %></td>
                  <td><%= stock.cantidad %></td>
                  <td><%= stock.created_at.strftime("%d/%m/%Y - %H:%M hs") %></td>
                </tr>
            <% end %>
            </tbody>
          </table>

app/views/stocks/new.html.erb
<%- model_class = Stock -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/stocks/show.html.erb
<%- model_class = Stock -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:cantidad) %>:</strong></dt>
  <dd><%= @stock.cantidad %></dd>
  <dt><strong><%= model_class.human_attribute_name(:producto_id) %>:</strong></dt>
  <dd><%= @stock.producto_id %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              stocks_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_stock_path(@stock), :class => 'btn btn-primary' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              stock_path(@stock),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>